version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      retries: 5
      timeout:
        5s
    restart: always

  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  client-frontend:
    build:
      context: ./client-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ingestion-service